name: "Run All Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      forceUpdates:
        description: "Forces a snapshot update"
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        python-version: ['2.7', '3.8', '3.10', '3.12', 'pypy3.8', 'pypy3.10', 'pypy3.12']
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.python-version }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run the tests
      run: |
        python -m aenum.test